export type MenuCategory =
  | "pizza-veg"
  | "pizza-non-veg"
  | "pizza-special"
  | "pizza-2in1"
  | "burger"
  | "footlong-sandwich"
  | "french-fries"
  | "garlic-bread"
  | "coffee-hot"
  | "coffee-cold"
  | "milkshake"
  | "mocktail"
  | "combo"
  | "dessert"

export interface MenuItem {
  id: string
  slug: string
  name: string
  category: MenuCategory
  categoryDisplay: string
  description: string
  descriptionLong: string
  price:
    | number
    | { S?: number; M?: number; L?: number; regular?: number; large?: number; "6inch"?: number; "12inch"?: number }
  image: string
  tags: string[]
  isVeg: boolean
  isHalal: boolean
  isPopular?: boolean
  keywords: string[]
}

export const MENU_ITEMS: MenuItem[] = [
  // VEG PIZZA
  {
    id: "margherita-pizza",
    slug: "margherita-pizza",
    name: "Margherita Pizza Veg",
    category: "pizza-veg",
    categoryDisplay: "Veg Pizza",
    description: "Pizza sauce, white cheese sauce, and mozzarella",
    descriptionLong:
      "A classic vegetarian delight made with hand-tossed homemade dough, layered with our signature pizza sauce and creamy white cheese sauce. Topped with premium mozzarella cheese for that perfect melt-in-mouth experience. A timeless favorite that combines simplicity with rich flavors, making it perfect for vegetarian pizza lovers in Mumbra and Shilphata. Served with garlic dip, ketchup, oregano, and chilli flakes at Shake Chilli Café & Pizzeria.",
    price: { S: 150, M: 280, L: 400 },
    image: "/images/pizza/veg/Margherita pizza Veg.jpg",
    tags: ["vegetarian", "classic", "white cheese sauce", "timeless", "homemade"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["margherita pizza veg mumbra", "best veg pizza shilphata", "vegetarian pizza near me", "classic veg pizza mumbra"],
  },
  {
    id: "double-cheese-margherita",
    slug: "double-cheese-margherita",
    name: "Double Cheese Margherita Veg",
    category: "pizza-veg",
    categoryDisplay: "Veg Pizza",
    description: "Pizza sauce, mozzarella, cheese, and filler cheese",
    descriptionLong:
      "A cheese lover's dream! Our Double Cheese Margherita is loaded with layers of premium mozzarella, regular cheese, and rich filler cheese on our signature pizza sauce base. Made with hand-tossed homemade dough for the ultimate cheese pull and creamy texture in every bite. Perfect for those who can't get enough cheese! Made fresh daily at our Shilphata location near Al-Hidaya School. Served with garlic dip, ketchup, oregano, and chilli flakes at Shake Chilli Café & Pizzeria in Mumbra.",
    price: { S: 180, M: 300, L: 420 },
    image: "/images/pizza/veg/Double cheese Margherita Veg.jpg",
    tags: ["vegetarian", "double cheese", "filler cheese", "cheese lover's dream", "creamy", "homemade"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["double cheese margherita veg mumbra", "extra cheese pizza shilphata", "cheese lover pizza near me", "filler cheese pizza mumbra"],
  },
  {
    id: "fresh-veggie-pizza",
    slug: "fresh-veggie-pizza",
    name: "Fresh Veggies Pizza Veg",
    category: "pizza-veg",
    categoryDisplay: "Veg Pizza",
    description: "Pizza sauce, tomato, onion, capsicum, mozzarella, and cheese sauce",
    descriptionLong:
      "A healthy and delicious option loaded with farm-fresh vegetables! Our Fresh Veggies Pizza features juicy tomatoes, crisp onions, and colorful capsicum on our signature pizza sauce base. Topped with premium mozzarella cheese and finished with a creamy cheese sauce drizzle. Made with hand-tossed homemade dough and the freshest vegetables sourced daily. Perfect for health-conscious pizza lovers who don't want to compromise on taste. Served with garlic dip, ketchup, oregano, and chilli flakes at Shake Chilli Café & Pizzeria in Mumbra and Shilphata.",
    price: { S: 200, M: 320, L: 440 },
    image: "/images/pizza/veg/Fresh veggies pizza Veg.jpg",
    tags: ["vegetarian", "healthy", "fresh vegetables", "farm-fresh", "cheese sauce", "homemade"],
    isVeg: true,
    isHalal: true,
    keywords: ["fresh veggies pizza veg mumbra", "healthy vegetable pizza shilphata", "fresh veg pizza near me", "capsicum pizza mumbra"],
  },
  {
    id: "corn-delight-pizza",
    slug: "corn-delight-pizza",
    name: "Corn Delight Pizza Veg",
    category: "pizza-veg",
    categoryDisplay: "Veg Pizza",
    description: "Pizza sauce, corn, onion, mozzarella, and cheese sauce",
    descriptionLong:
      "A favorite among kids and adults alike! Our Corn Delight Pizza features sweet corn kernels and fresh onions on our signature pizza sauce base, topped with premium mozzarella cheese and finished with a drizzle of creamy cheese sauce. Made with hand-tossed homemade dough for that perfect texture. A delightful combination of sweetness from corn and savory flavors that creates an irresistible taste experience. Served with garlic dip, ketchup, oregano, and chilli flakes at Shake Chilli Café & Pizzeria in Mumbra.",
    price: { S: 220, M: 340, L: 460 },
    image: "/images/pizza/veg/CORN DELIGHT PIZZA VEG.jpg",
    tags: ["vegetarian", "sweet corn", "family favorite", "cheese sauce", "homemade", "delightful"],
    isVeg: true,
    isHalal: true,
    keywords: ["corn delight pizza veg mumbra", "sweet corn pizza shilphata", "kids pizza near me", "cheese sauce pizza mumbra"],
  },
  {
    id: "paneer-pizza",
    slug: "paneer-pizza",
    name: "Mixed Paneer Pizza Veg",
    category: "pizza-veg",
    categoryDisplay: "Veg Pizza",
    description: "Pizza sauce, onion, capsicum, tomato, paneer, mozzarella, and cheese sauce",
    descriptionLong:
      "A fusion of Italian and Indian flavors! Our Mixed Paneer Pizza features fresh paneer cubes perfectly combined with crisp onions, colorful capsicum, and juicy tomatoes on our signature pizza sauce base. Topped with premium mozzarella cheese and finished with a drizzle of creamy cheese sauce. Made with hand-tossed homemade dough and the finest quality paneer. One of the most popular vegetarian pizzas in Mumbra and Shilphata, perfect for those who love the rich taste of paneer with fresh vegetables. Served with garlic dip, ketchup, oregano, and chilli flakes at Shake Chilli Café & Pizzeria.",
    price: { S: 250, M: 370, L: 500 },
    image: "/images/pizza/veg/Mixed paneer pizza Veg.jpg",
    tags: ["vegetarian", "paneer", "mixed vegetables", "indian fusion", "cheese sauce", "homemade"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["mixed paneer pizza veg mumbra", "paneer vegetable pizza shilphata", "best paneer pizza near me", "paneer cheese sauce pizza mumbra"],
  },
  {
    id: "veg-veganza",
    slug: "veg-veganza",
    name: "Veg Veganza Pizza Veg",
    category: "pizza-veg",
    categoryDisplay: "Veg Pizza",
    description: "Pizza sauce, tomato, onion, capsicum, paneer, corn, olive, jalapeño, mozzarella, and cheese sauce",
    descriptionLong:
      "The ultimate loaded vegetarian pizza experience! Our premium Veg Veganza features a rich medley of fresh vegetables including juicy tomatoes, crisp onions, colorful capsicum, sweet corn, and premium paneer cubes. Enhanced with tangy olives and spicy jalapeños for that perfect flavor kick, all on our signature pizza sauce base. Topped with premium mozzarella cheese and finished with a generous drizzle of creamy cheese sauce. Made with hand-tossed homemade dough, this gourmet vegetarian masterpiece is perfect for special occasions or when you want to treat yourself to the finest. Served with garlic dip, ketchup, oregano, and chilli flakes at Shake Chilli Café & Pizzeria in Mumbra and Shilphata.",
    price: { S: 300, M: 420, L: 550 },
    image: "/images/pizza/veg/VEG vegenza pizza Veg.jpg",
    tags: ["vegetarian", "premium", "gourmet", "loaded", "ultimate", "medley", "masterpiece", "cheese sauce"],
    isVeg: true,
    isHalal: true,
    keywords: ["veg veganza pizza veg mumbra", "loaded vegetarian pizza shilphata", "premium veg pizza near me", "gourmet veggie pizza mumbra", "ultimate veg pizza"],
  },

  // NON-VEG PIZZA
  {
    id: "chicken-tikka-pizza",
    slug: "chicken-tikka-pizza",
    name: "Chicken Tikka Pizza",
    category: "pizza-non-veg",
    categoryDisplay: "Non-Veg Pizza",
    description: "Pizza sauce, mozzarella, chicken tikka, and creamy cheese sauce",
    descriptionLong:
      "Crafted with homemade dough and layered with our signature pizza sauce, spicy chicken tikka, mozzarella cheese, and a drizzle of creamy white cheese sauce. Served with garlic dip, ketchup, oregano, and chilli flakes for the perfect finish. Made with 100% halal chicken. The most popular non-veg pizza in Mumbra, Shilphata, and Diva.",
    price: { S: 200, M: 350, L: 480 },
    image: "/images/pizza/Chicken tikka pizza.jpg",
    tags: ["non-vegetarian", "chicken", "tikka", "bestseller", "cheese sauce", "garlic dip"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["chicken tikka pizza mumbra", "best chicken pizza shilphata", "halal pizza near me", "chicken tikka pizza with cheese sauce"],
  },
  {
    id: "chicken-spicy-pizza",
    slug: "chicken-spicy-pizza",
    name: "Peri Peri Chicken Pizza",
    category: "pizza-non-veg",
    categoryDisplay: "Non-Veg Pizza",
    description: "Pizza sauce, onion, peri peri masala, chicken, and mozzarella",
    descriptionLong:
      "Savor the spicy goodness of our Peri Peri Chicken Pizza, made with fresh homemade pizza dough and our signature house-made pizza sauce. Topped with juicy, mildly spicy chicken, fresh onions, and a flavorful touch of peri peri masala, this pizza delivers the perfect mix of spicy, cheesy, and creamy flavors. Finished with a generous layer of mozzarella cheese and our smooth white cheese sauce. Everything from the sauce to the toppings is freshly prepared in our kitchen. Served with garlic dip, ketchup, oregano, and chili flakes for the perfect café-style experience. Made with 100% halal chicken at Shake Chilli Café & Pizzeria in Mumbra.",
    price: { S: 240, M: 370, L: 500 },
    image: "/images/pizza/Chicken Spicy pizza.jpg",
    tags: ["non-vegetarian", "chicken", "spicy", "peri peri", "homemade", "fresh", "garlic dip"],
    isVeg: false,
    isHalal: true,
    keywords: ["peri peri chicken pizza mumbra", "spicy chicken pizza shilphata", "homemade pizza mumbra", "peri peri pizza near me", "fresh pizza mumbra"],
  },
  {
    id: "bbq-pizza",
    slug: "bbq-pizza",
    name: "BBQ Pizza",
    category: "pizza-non-veg",
    categoryDisplay: "Non-Veg Pizza",
    description: "BBQ chicken with smoky sauce and cheese",
    descriptionLong:
      "Smoky and delicious! Our BBQ Pizza features tender chicken pieces marinated in BBQ sauce, topped with onions and mozzarella. Made with 100% halal chicken. A favorite in Mumbra, Shilphata, and nearby areas.",
    price: { S: 250, M: 400, L: 530 },
    image: "/images/pizza/CHICKEN BBQ PIZZA.jpg",
    tags: ["non-vegetarian", "chicken", "bbq", "smoky"],
    isVeg: false,
    isHalal: true,
    keywords: ["bbq pizza mumbra", "bbq chicken pizza shilphata", "best bbq pizza near me"],
  },
  {
    id: "chicken-garlic-pizza",
    slug: "chicken-garlic-pizza",
    name: "Chicken Garlic Pizza",
    category: "pizza-non-veg",
    categoryDisplay: "Non-Veg Pizza",
    description: "Pizza sauce, cheese, mozzarella, garlic sauce, and garlic flavour chicken",
    descriptionLong:
      "A garlic lover's paradise! Our Chicken Garlic Pizza features tender garlic-flavoured chicken on a rich pizza sauce base, generously topped with mozzarella and cheese. Enhanced with aromatic garlic sauce that infuses every bite with bold, savory flavours. The perfect combination of juicy chicken and intense garlic creates an irresistible taste experience. Made with 100% halal chicken and served with garlic dip, ketchup, oregano, and chilli flakes. A must-try for garlic enthusiasts at Shake Chilli Café & Pizzeria in Mumbra!",
    price: { S: 270, M: 420, L: 550 },
    image: "/images/pizza/Chicken garlic pizza.jpg",
    tags: ["non-vegetarian", "chicken", "garlic", "savory", "aromatic", "garlic lover's paradise"],
    isVeg: false,
    isHalal: true,
    keywords: ["chicken garlic pizza mumbra", "garlic pizza shilphata", "garlic lover pizza near me", "savory chicken pizza mumbra", "aromatic pizza"],
  },
  {
    id: "golden-delight-pizza",
    slug: "golden-delight-pizza",
    name: "Chicken Golden Delight Pizza",
    category: "pizza-non-veg",
    categoryDisplay: "Non-Veg Pizza",
    description: "Pizza sauce, chicken, corn, mozzarella, and cheese sauce",
    descriptionLong:
      "Homemade dough topped with juicy chicken, sweet corn, pizza sauce, and mozzarella. Cheesy, flavorful, and satisfying — a golden favorite in Mumbra! Made with 100% halal chicken and fresh ingredients daily at Shake Chilli Café & Pizzeria. This signature creation combines the perfect balance of protein, sweetness from corn, and rich cheese flavors.",
    price: { S: 300, M: 450, L: 580 },
    image: "/images/pizza/CHICKEN GOLDEN DELIGHT PIZZA.jpg",
    tags: ["non-vegetarian", "chicken", "corn", "homemade", "signature", "cheese sauce"],
    isVeg: false,
    isHalal: true,
    keywords: ["chicken golden delight pizza mumbra", "golden delight pizza shilphata", "homemade chicken pizza mumbra", "corn chicken pizza near me"],
  },
  {
    id: "chicken-vegenza",
    slug: "chicken-vegenza",
    name: "Chicken Vegenza Pizza",
    category: "pizza-non-veg",
    categoryDisplay: "Non-Veg Pizza",
    description: "Chicken, pizza sauce, onion, capsicum, tomato, peri peri masala, mozzarella, and cheese sauce",
    descriptionLong:
      "Homemade dough topped with spicy tikka chicken, onions, capsicum, tomatoes, peri peri masala, mozzarella, and cheese sauce. Spicy, cheesy, and full of flavor — a Mumbra favorite! Made with 100% halal chicken and fresh vegetables daily at Shake Chilli Café & Pizzeria. This loaded pizza combines the perfect blend of spices, vegetables, and cheese for an unforgettable taste experience.",
    price: { S: 350, M: 500, L: 630 },
    image: "/images/pizza/Chicken vegenza pizza.jpg",
    tags: ["non-vegetarian", "chicken", "loaded", "spicy", "tikka", "peri peri", "vegetables", "cheese sauce"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["chicken vegenza pizza mumbra", "spicy chicken pizza shilphata", "loaded pizza mumbra", "tikka chicken pizza near me", "peri peri vegenza pizza"],
  },
  {
    id: "chicken-italian",
    slug: "chicken-italian",
    name: "Italian Chicken Pizza",
    category: "pizza-non-veg",
    categoryDisplay: "Non-Veg Pizza",
    description: "Italian flavour chicken, capsicum, olive, jalapeño, mozzarella, cheese filler, and cheese sauce",
    descriptionLong:
      "A rich and indulgent Italian-style pizza loaded with layers of mozzarella and creamy cheese filler, topped with juicy Italian-flavoured chicken, fresh capsicum, olives, and spicy jalapeños. Finished with a drizzle of our signature white cheese sauce for that perfect cheesy melt-in-mouth bite. Made with 100% halal chicken at Shake Chilli Café & Pizzeria in Mumbra for an authentic Italian experience.",
    price: { S: 380, M: 530, L: 660 },
    image: "/images/pizza/Italian chicken pizza.jpg",
    tags: ["non-vegetarian", "chicken", "italian", "gourmet", "cheese filler", "jalapeño", "olives", "indulgent"],
    isVeg: false,
    isHalal: true,
    keywords: ["italian chicken pizza mumbra", "gourmet pizza shilphata", "cheese filled pizza mumbra", "italian style pizza near me", "rich chicken pizza mumbra"],
  },
  {
    id: "chicken-mexican-pizza",
    slug: "chicken-mexican-pizza",
    name: "Chicken Mexican Pizza",
    category: "pizza-non-veg",
    categoryDisplay: "Non-Veg Pizza",
    description: "Chicken, capsicum, onion, mozzarella, filler, and cheese sauce",
    descriptionLong:
      "A bold and cheesy double-layer pizza inspired by authentic Mexican flavours. Packed with a generous layer of spiced chicken, gooey mozzarella, and creamy cheese between two thin crusts — then loaded again with extra cheese and toppings on top. Every bite bursts with rich, smoky Mexican taste and irresistible cheesiness. Made with 100% halal chicken. Served with garlic dip, ketchup, oregano, and chilli flakes for the complete Mexican experience at Shake Chilli Café & Pizzeria in Mumbra.",
    price: { S: 420, M: 570, L: 700 },
    image: "/images/pizza/Chicken mexican pizza.jpg",
    tags: ["non-vegetarian", "chicken", "mexican", "double-layer", "bold", "cheesy", "smoky", "garlic dip"],
    isVeg: false,
    isHalal: true,
    keywords: ["chicken mexican pizza mumbra", "double layer pizza shilphata", "mexican pizza near me", "smoky chicken pizza mumbra", "bold flavour pizza"],
  },

  // SPECIAL PIZZA
  {
    id: "mamamia-pizza",
    slug: "mamamia-pizza",
    name: "Chicken Mamamia Pizza",
    category: "pizza-special",
    categoryDisplay: "Special Pizza",
    description: "3 different flavours chicken, capsicum, onion, olive, jalapeño, tomato, mozzarella, cheese filler, and cheese sauce",
    descriptionLong:
      "A premium pizza loaded with three irresistible chicken flavours layered over a rich bed of mozzarella and cheese filler. Topped with fresh veggies — capsicum, onion, olives, jalapeños, and tomato — and finished with a drizzle of creamy cheese sauce for the ultimate cheesy, flavour-packed bite. Made with 100% halal chicken. Served with garlic dip, ketchup, oregano, and chilli flakes. The legendary Mamamia Pizza experience at Shake Chilli Café & Pizzeria in Mumbra!",
    price: { S: 480, M: 630, L: 750 },
    image: "/images/pizza/Chicken mamamia pizza.jpg",
    tags: ["special", "premium", "signature", "bestseller", "three flavours", "cheese filler", "fresh veggies", "ultimate"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["chicken mamamia pizza mumbra", "three flavour chicken pizza shilphata", "premium special pizza near me", "best loaded pizza mumbra", "mamamia pizza"],
  },
  {
    id: "7g-pizza",
    slug: "7g-pizza",
    name: "7th G Pizza",
    category: "pizza-special",
    categoryDisplay: "Special Pizza",
    description: "Pizza sauce, 3 different flavours of chicken, side crust stuffed with chicken and cheese, mozzarella, olive and jalapeño",
    descriptionLong:
      "A chef's special creation featuring three bold chicken flavours on a rich pizza sauce base, topped with loads of mozzarella and creamy cheese. The golden crust is stuffed with juicy chicken and molten cheese, making every bite a burst of flavour — cheesy, meaty, and perfectly seasoned with olives and jalapeños for that final kick. Made with 100% halal chicken. Served with garlic dip, ketchup, oregano, and chilli flakes. The ultimate chef's masterpiece at Shake Chilli Café & Pizzeria in Mumbra!",
    price: { S: 500, M: 650, L: 780 },
    image: "/images/pizza/7th G pizza.jpg",
    tags: ["special", "chef's special", "premium", "stuffed crust", "three flavours", "bold", "burst of flavour"],
    isVeg: false,
    isHalal: true,
    keywords: ["7th g pizza mumbra", "stuffed crust pizza shilphata", "chef special pizza near me", "three chicken flavours mumbra", "bold pizza mumbra"],
  },
  {
    id: "8g-pizza",
    slug: "8g-pizza",
    name: "8G Pizza",
    category: "pizza-special",
    categoryDisplay: "Special Pizza",
    description: "Eight gourmet toppings for the ultimate pizza experience",
    descriptionLong:
      "Take it to the next level with our 8G Pizza! Eight premium gourmet toppings, multiple cheese varieties, and our signature sauce. The ultimate pizza experience in Mumbra and Shilphata. Perfect for pizza enthusiasts who want it all.",
    price: { S: 550, M: 700, L: 820 },
    image: "/images/pizza/DOUBLE LAYER PIZZA.jpg",
    tags: ["special", "gourmet", "premium", "ultimate"],
    isVeg: false,
    isHalal: true,
    keywords: ["ultimate pizza mumbra", "8g pizza shilphata", "premium pizza near me"],
  },
  {
    id: "double-layer-pizza",
    slug: "double-layer-pizza",
    name: "Double Layer Pizza",
    category: "pizza-special",
    categoryDisplay: "Special Pizza",
    description: "2 layer of base, pizza sauce, 3 different flavours chicken, 3 different types of mozzarella and cheese",
    descriptionLong:
      "Our heaviest and most indulgent pizza — a true cheese and chicken lover's dream. Built with a double-layer crust, loaded between and above with three bold chicken flavours and a rich fusion of triple cheese. Every bite delivers unmatched cheesiness, juicy chicken, and a melt-in-mouth experience that defines premium perfection. Made with 100% halal chicken. Served with garlic dip, ketchup, oregano, and chilli flakes. The ultimate indulgence at Shake Chilli Café & Pizzeria in Mumbra!",
    price: { S: 600, M: 750, L: 870 },
    image: "/images/pizza/DOUBLE LAYER PIZZA.jpg",
    tags: ["special", "heaviest", "indulgent", "double-layer", "triple cheese", "three flavours", "premium perfection", "cheese lover's dream"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["double layer pizza mumbra", "heaviest pizza shilphata", "triple cheese pizza near me", "indulgent pizza mumbra", "cheese lover pizza"],
  },
  {
    id: "big-shakechilli-burger",
    slug: "big-shakechilli-burger",
    name: "Big ShakeChilli Burger",
    category: "burger",
    categoryDisplay: "Burger",
    description: "Our signature double-patty monster burger",
    descriptionLong:
      "The biggest, baddest burger in Mumbra! Our signature Big ShakeChilli Burger features two juicy halal chicken patties, double cheese, fresh vegetables, and our secret sauce. A meal in itself! Perfect for those with a big appetite in Shilphata and surrounding areas.",
    price: 180,
    image: "/images/burger/big-shakechilli.jpg",
    tags: ["non-vegetarian", "chicken", "double", "signature", "large"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["big burger mumbra", "double patty burger shilphata", "best burger near me"],
  },

  // Add more items for other categories...
  // (I'll add a few key items from each category to keep the response manageable)

  // FOOTLONG SANDWICH
  {
    id: "veg-subway",
    slug: "veg-subway",
    name: "Veg Subway",
    category: "footlong-sandwich",
    categoryDisplay: "Footlong Sandwich",
    description: "Fresh vegetable sandwich subway style",
    descriptionLong:
      "Our Veg Subway features fresh vegetables, cheese, and sauces in a freshly baked footlong bread. Available in 6-inch and 12-inch sizes. Perfect for a healthy meal in Mumbra and Shilphata.",
    price: { "6inch": 140, "12inch": 250 },
    image: "/images/sandwich/veg-subway.jpg",
    tags: ["vegetarian", "healthy", "subway-style"],
    isVeg: true,
    isHalal: true,
    keywords: ["veg sandwich mumbra", "subway shilphata", "footlong sandwich near me"],
  },
  {
    id: "chicken-subway",
    slug: "chicken-subway",
    name: "Chicken Subway",
    category: "footlong-sandwich",
    categoryDisplay: "Footlong Sandwich",
    description: "Grilled chicken sandwich with fresh veggies",
    descriptionLong:
      "Our Chicken Subway features tender grilled halal chicken, fresh vegetables, cheese, and your choice of sauces in freshly baked bread. Available in 6-inch and 12-inch. The best chicken sandwich in Mumbra and Shilphata!",
    price: { "6inch": 160, "12inch": 280 },
    image: "/images/sandwich/chicken-subway.jpg",
    tags: ["non-vegetarian", "chicken", "subway-style"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["chicken sandwich mumbra", "halal sandwich shilphata", "best sandwich near me"],
  },

  // COFFEE
  {
    id: "cappuccino",
    slug: "cappuccino",
    name: "Cappuccino",
    category: "coffee-hot",
    categoryDisplay: "Hot Coffee",
    description: "Classic Italian cappuccino with perfect foam",
    descriptionLong:
      "Our Cappuccino is made with premium coffee beans, steamed milk, and perfect foam art. The best coffee in Mumbra and Shilphata. Perfect for coffee lovers who appreciate quality.",
    price: 70,
    image: "/images/coffee/cappuccino.jpg",
    tags: ["coffee", "hot", "classic"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["cappuccino mumbra", "best coffee shilphata", "coffee near me"],
  },
  {
    id: "iced-cappuccino",
    slug: "iced-cappuccino",
    name: "Iced Cappuccino",
    category: "coffee-cold",
    categoryDisplay: "Cold Coffee",
    description: "Refreshing iced cappuccino perfect for hot days",
    descriptionLong:
      "Beat the heat with our Iced Cappuccino! Made with premium coffee, cold milk, and ice. The perfect refreshing drink in Mumbra and Shilphata. Great for hot summer days!",
    price: 150,
    image: "/images/coffee/iced-cappuccino.jpg",
    tags: ["coffee", "cold", "refreshing"],
    isVeg: true,
    isHalal: true,
    keywords: ["iced coffee mumbra", "cold coffee shilphata", "iced cappuccino near me"],
  },

  // MILKSHAKES
  {
    id: "chocolate-shake",
    slug: "chocolate-shake",
    name: "Chocolate Shake",
    category: "milkshake",
    categoryDisplay: "Milkshake",
    description: "Rich and creamy chocolate milkshake",
    descriptionLong:
      "Indulge in our rich Chocolate Shake made with premium chocolate and fresh milk. Thick, creamy, and absolutely delicious. The best milkshake in Mumbra and Shilphata!",
    price: 120,
    image: "/images/milkshake/chocolate.jpg",
    tags: ["milkshake", "chocolate", "dessert"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["chocolate shake mumbra", "milkshake shilphata", "best shake near me"],
  },

  // MOCKTAILS
  {
    id: "virgin-mojito",
    slug: "virgin-mojito",
    name: "Virgin Mojito",
    category: "mocktail",
    categoryDisplay: "Mocktail",
    description: "Refreshing mint and lime mocktail",
    descriptionLong:
      "Our Virgin Mojito is the perfect refreshing drink with fresh mint, lime, and soda. The most popular mocktail in Mumbra and Shilphata. Perfect for any time of the day!",
    price: 80,
    image: "/images/mocktail/virgin-mojito.jpg",
    tags: ["mocktail", "refreshing", "mint"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["mojito mumbra", "mocktail shilphata", "virgin mojito near me"],
  },

  // GARLIC BREAD
  {
    id: "cheese-garlic-bread",
    slug: "cheese-garlic-bread",
    name: "Cheese Garlic Bread",
    category: "garlic-bread",
    categoryDisplay: "Garlic Bread",
    description: "Dough, mozzarella, white cheese sauce, oregano, butter, and garlic paste",
    descriptionLong:
      "This garlic bread is made using homemade dough, generously topped with premium mozzarella cheese and drizzled with creamy white cheese sauce. Enhanced with aromatic oregano, rich butter, and fresh garlic paste for that perfect garlic flavor. Baked to golden perfection, creating a crispy outside and soft, cheesy inside. A perfect side dish or snack that complements any meal. Made fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata for the ultimate comfort food experience.",
    price: { regular: 120, large: 180 },
    image: "/images/bread/Cheese garlic bread.jpg",
    tags: ["garlic bread", "cheese", "homemade", "aromatic", "comfort food", "side dish"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["cheese garlic bread mumbra", "garlic bread shilphata", "homemade garlic bread near me", "cheesy bread mumbra"],
  },
  {
    id: "corn-garlic-bread",
    slug: "corn-garlic-bread",
    name: "Corn Garlic Bread",
    category: "garlic-bread",
    categoryDisplay: "Garlic Bread",
    description: "Dough, mozzarella, corn, white cheese sauce, oregano, butter, and garlic paste",
    descriptionLong:
      "A delightful twist on classic garlic bread! Made with homemade dough and topped with premium mozzarella cheese, sweet corn kernels, and creamy white cheese sauce. Enhanced with aromatic oregano, rich butter, and fresh garlic paste for that perfect garlic flavor. The sweet corn adds a burst of flavor and texture, making every bite a delicious experience. Baked to golden perfection with a crispy outside and soft, cheesy inside. Perfect as a side dish or snack. Made fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata.",
    price: { regular: 140, large: 200 },
    image: "/images/bread/CORN GARLIC BREAD.jpg",
    tags: ["garlic bread", "corn", "sweet", "cheese", "homemade", "aromatic", "side dish"],
    isVeg: true,
    isHalal: true,
    keywords: ["corn garlic bread mumbra", "sweet corn bread shilphata", "corn cheese bread near me", "garlic bread with corn mumbra"],
  },
  {
    id: "paneer-garlic-bread",
    slug: "paneer-garlic-bread",
    name: "Paneer Garlic Bread",
    category: "garlic-bread",
    categoryDisplay: "Garlic Bread",
    description: "Dough, mozzarella, white cheese sauce, oregano, butter, garlic paste, and paneer",
    descriptionLong:
      "An Indian fusion delight that combines the best of both worlds! Made with homemade dough and loaded with premium mozzarella cheese and fresh paneer cubes, drizzled with creamy white cheese sauce. Enhanced with aromatic oregano, rich butter, and fresh garlic paste. The soft paneer adds a rich, creamy texture that melts in your mouth alongside the garlic flavors. Baked to perfection with a golden crispy crust. A perfect fusion of Italian garlic bread and Indian flavors. Made fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata.",
    price: { regular: 160, large: 220 },
    image: "/images/bread/Paneer garlic bread.jpg",
    tags: ["garlic bread", "paneer", "indian fusion", "cheese", "homemade", "creamy", "fusion"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["paneer garlic bread mumbra", "indian garlic bread shilphata", "paneer cheese bread near me", "fusion bread mumbra"],
  },
  {
    id: "veg-garlic-bread",
    slug: "veg-garlic-bread",
    name: "Veg Garlic Bread",
    category: "garlic-bread",
    categoryDisplay: "Garlic Bread",
    description: "Dough, mozzarella, white cheese sauce, oregano, butter, garlic paste, tomato, and capsicum",
    descriptionLong:
      "A colorful and healthy twist on classic garlic bread! Made with homemade dough and topped with premium mozzarella cheese, fresh tomato chunks, and crisp capsicum pieces, all drizzled with creamy white cheese sauce. Enhanced with aromatic oregano, rich butter, and fresh garlic paste. The fresh vegetables add vibrant colors, nutrients, and a delightful crunch to complement the rich garlic and cheese flavors. Baked to golden perfection for a crispy outside and soft, veggie-loaded inside. Perfect for health-conscious food lovers. Made fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata.",
    price: { regular: 150, large: 210 },
    image: "/images/bread/VEG GARLIC BREAD.jpg",
    tags: ["garlic bread", "vegetables", "healthy", "colorful", "cheese", "homemade", "nutritious", "fresh"],
    isVeg: true,
    isHalal: true,
    keywords: ["veg garlic bread mumbra", "vegetable bread shilphata", "healthy garlic bread near me", "veggie bread mumbra"],
  },
  {
    id: "chicken-garlic-bread",
    slug: "chicken-garlic-bread",
    name: "Chicken Garlic Bread",
    category: "garlic-bread",
    categoryDisplay: "Garlic Bread",
    description: "Dough, mozzarella, white cheese sauce, oregano, butter, garlic paste, chicken, tomato, and capsicum",
    descriptionLong:
      "The ultimate non-vegetarian garlic bread experience! Made with homemade dough and loaded with tender, juicy chicken pieces, premium mozzarella cheese, fresh tomato chunks, and crisp capsicum. All drizzled with creamy white cheese sauce and enhanced with aromatic oregano, rich butter, and fresh garlic paste. The combination of succulent halal chicken with fresh vegetables creates a perfect balance of flavors and textures. Baked to golden perfection with a crispy outside and a hearty, protein-packed inside. A complete meal in itself! Made fresh daily with 100% halal chicken at Shake Chilli Café & Pizzeria in Mumbra and Shilphata.",
    price: { regular: 180, large: 240 },
    image: "/images/bread/CHICKEN GARLIC BREAD.jpg",
    tags: ["garlic bread", "chicken", "non-vegetarian", "protein", "hearty", "complete meal", "halal"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["chicken garlic bread mumbra", "non veg bread shilphata", "halal garlic bread near me", "protein bread mumbra"],
  },

  // BURGERS
  {
    id: "aloo-tikki-burger",
    slug: "aloo-tikki-burger",
    name: "Aloo Tikki Burger",
    category: "burger",
    categoryDisplay: "Burger",
    description: "Burger bun, aloo tikka patty, sauces, mayo, onion, and tomato (cheese slice extra charge if added)",
    descriptionLong:
      "A classic Indian-style burger that's loved by everyone! Our Aloo Tikki Burger features a crispy, golden aloo tikka patty made from perfectly spiced potatoes, served in a soft burger bun with fresh onion slices and juicy tomato. Enhanced with our special sauces and creamy mayo for that perfect flavor combination. A vegetarian delight that's both filling and delicious. Add a cheese slice for extra indulgence (additional charges apply). Made fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata. Perfect for a quick, tasty meal!",
    price: 80,
    image: "/images/burger/ALOO TIKKI BURGER.jpg",
    tags: ["burger", "aloo tikki", "vegetarian", "indian style", "crispy", "spiced", "quick meal"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["aloo tikki burger mumbra", "veg burger shilphata", "potato burger near me", "indian burger mumbra"],
  },
  {
    id: "chicken-burst-burger",
    slug: "chicken-burst-burger",
    name: "Chicken Burst Burger",
    category: "burger",
    categoryDisplay: "Burger",
    description: "Burger bun, sauces, cheese slice, cheese sauce, chicken double patty (soft and spicy), lettuce",
    descriptionLong:
      "Get ready for an explosion of flavors with our Chicken Burst Burger! This premium non-vegetarian burger features not one, but TWO soft and spicy chicken patties that will make your taste buds dance. Served in a fresh burger bun with a generous cheese slice and our signature cheese sauce for that extra creamy indulgence. Enhanced with our special sauces and topped with crisp, fresh lettuce for the perfect crunch. The double chicken patties are perfectly seasoned with aromatic spices, making each bite a burst of juicy, tender chicken goodness. Made with 100% halal chicken and prepared fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata. A must-try for all chicken lovers!",
    price: 150,
    image: "/images/burger/CHICKEN BURST BURGER.jpg",
    tags: ["burger", "chicken", "non-vegetarian", "double patty", "spicy", "cheese sauce", "premium", "halal"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["chicken burst burger mumbra", "double patty burger shilphata", "spicy chicken burger near me", "halal burger mumbra"],
  },
  {
    id: "chicken-burger",
    slug: "chicken-burger",
    name: "Chicken Burger",
    category: "burger",
    categoryDisplay: "Burger",
    description: "Burger bun, sauces, chicken patty (soft and spicy), lettuce (cheese slice extra charge)",
    descriptionLong:
      "A classic chicken burger that delivers on taste and satisfaction! Our Chicken Burger features a perfectly seasoned, soft and spicy chicken patty that's juicy and tender in every bite. Served in a fresh, soft burger bun with our signature sauces and topped with crisp, fresh lettuce for that perfect crunch. The chicken patty is marinated with aromatic spices and cooked to perfection, ensuring a burst of flavors with each bite. Add a cheese slice for extra richness and indulgence (additional charges apply). Made with 100% halal chicken and prepared fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata. Perfect for those who love the classic chicken burger experience!",
    price: 120,
    image: "/images/burger/Chicken burger.jpg",
    tags: ["burger", "chicken", "non-vegetarian", "classic", "spicy", "soft patty", "halal"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["chicken burger mumbra", "classic chicken burger shilphata", "spicy burger near me", "halal chicken burger mumbra"],
  },
  {
    id: "zinger-burger",
    slug: "zinger-burger",
    name: "Zinger Burger",
    category: "burger",
    categoryDisplay: "Burger",
    description: "Burger bun, sauces, crispy chicken patty, lettuce (cheese slice extra charge)",
    descriptionLong:
      "Experience the ultimate crunch with our signature Zinger Burger! This premium burger features a perfectly crispy chicken patty that's golden-brown on the outside and juicy on the inside, delivering an incredible texture contrast in every bite. The crispy coating is seasoned with our special blend of spices for that authentic zinger kick. Served in a fresh, soft burger bun with our signature sauces and topped with crisp, fresh lettuce for added freshness. The crispy chicken patty is made from tender chicken pieces, coated in our secret spice mix and fried to perfection. Add a cheese slice for extra indulgence (additional charges apply). Made with 100% halal chicken and prepared fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata. Perfect for those who love that satisfying crunch!",
    price: 130,
    image: "/images/burger/Xinger burger.jpg",
    tags: ["burger", "zinger", "chicken", "non-vegetarian", "crispy", "crunchy", "spicy", "halal"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["zinger burger mumbra", "crispy chicken burger shilphata", "crunchy burger near me", "halal zinger mumbra"],
  },

  // SANDWICHES
  {
    id: "veg-footlong-sandwich",
    slug: "veg-footlong-sandwich",
    name: "Veg Footlong Sandwich",
    category: "footlong-sandwich",
    categoryDisplay: "Footlong Sandwich",
    description: "Footlong bun, lettuce, cheese slice, onion, tomato, jalapeño, beetroot, sauces",
    descriptionLong:
      "Satisfy your hunger with our generous Veg Footlong Sandwich! This submarine-style sandwich is packed with fresh, healthy vegetables and served in a soft, freshly baked footlong bun. Loaded with crisp lettuce, premium cheese slice, fresh onion rings, juicy tomato slices, tangy jalapeños, and colorful beetroot for that perfect crunch and nutrition. Enhanced with our signature sauces that bring all the flavors together beautifully. This wholesome vegetarian delight is not just filling but also nutritious, making it perfect for a complete meal. The combination of fresh vegetables provides a variety of textures and flavors in every bite. Made fresh daily with the finest ingredients at Shake Chilli Café & Pizzeria in Mumbra and Shilphata. A healthy and delicious choice for vegetarian food lovers!",
    price: 120,
    image: "/images/sandwhich/VEG FOOTLONG SANDWHICH.jpg",
    tags: ["sandwich", "footlong", "vegetarian", "healthy", "fresh vegetables", "submarine", "nutritious"],
    isVeg: true,
    isHalal: true,
    isPopular: true,
    keywords: ["veg footlong sandwich mumbra", "submarine sandwich shilphata", "healthy sandwich near me", "vegetarian footlong mumbra"],
  },
  {
    id: "chicken-footlong-sandwich",
    slug: "chicken-footlong-sandwich",
    name: "Chicken Footlong Sandwich",
    category: "footlong-sandwich",
    categoryDisplay: "Footlong Sandwich",
    description: "Footlong bun, lettuce, cheese slice, onion, tomato, jalapeño, chicken, sauces",
    descriptionLong:
      "Indulge in our protein-packed Chicken Footlong Sandwich! This generous submarine-style sandwich features tender, juicy chicken pieces perfectly seasoned and cooked to perfection, served in a soft, freshly baked footlong bun. Loaded with crisp lettuce, premium cheese slice, fresh onion rings, juicy tomato slices, and tangy jalapeños for that perfect balance of flavors and textures. Enhanced with our signature sauces that complement the succulent chicken beautifully. This hearty non-vegetarian delight is not just filling but also protein-rich, making it perfect for a complete, satisfying meal. The combination of tender chicken with fresh vegetables provides a variety of textures and flavors in every bite. Made with 100% halal chicken and prepared fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata. A delicious choice for chicken lovers who want a substantial meal!",
    price: 150,
    image: "/images/sandwhich/Chicken footlong sandwhich .jpg",
    tags: ["sandwich", "footlong", "chicken", "non-vegetarian", "protein", "submarine", "hearty", "halal"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["chicken footlong sandwich mumbra", "non veg submarine sandwich shilphata", "protein sandwich near me", "halal footlong mumbra"],
  },
  {
    id: "crispy-footlong-sandwich",
    slug: "crispy-footlong-sandwich",
    name: "Crispy Footlong Sandwich",
    category: "footlong-sandwich",
    categoryDisplay: "Footlong Sandwich",
    description: "Footlong bun, crispy chicken patty, lettuce, cheese slice, onion, tomato, jalapeño, mayo, special sauces",
    descriptionLong:
      "Experience the ultimate crunch with our Crispy Footlong Sandwich! This premium submarine-style sandwich features a perfectly golden-brown crispy chicken patty that's crunchy on the outside and juicy on the inside, delivering an incredible texture contrast in every bite. The crispy coating is seasoned with our special blend of spices for that authentic crunch you'll crave. Served in a soft, freshly baked footlong bun and loaded with crisp lettuce, premium cheese slice, fresh onion rings, juicy tomato slices, and tangy jalapeños. Enhanced with creamy mayo and our signature special sauces that perfectly complement the crispy chicken. This hearty non-vegetarian delight combines the satisfaction of crispy fried chicken with the freshness of vegetables in one generous sandwich. Made with 100% halal chicken and prepared fresh daily at Shake Chilli Café & Pizzeria in Mumbra and Shilphata. Perfect for those who love that satisfying crunch in a filling meal!",
    price: 170,
    image: "/images/sandwhich/Crispy footlong sandwhich.jpg",
    tags: ["sandwich", "footlong", "crispy chicken", "non-vegetarian", "crunchy", "premium", "submarine", "halal"],
    isVeg: false,
    isHalal: true,
    isPopular: true,
    keywords: ["crispy footlong sandwich mumbra", "crunchy chicken sandwich shilphata", "crispy sandwich near me", "halal crispy footlong mumbra"],
  },
]

export const MENU_CATEGORIES = [
  { id: "pizza-veg", name: "Veg Pizza", slug: "pizza", icon: "🍕" },
  { id: "pizza-non-veg", name: "Non-Veg Pizza", slug: "pizza", icon: "🍕" },
  { id: "burger", name: "Burgers", slug: "burger", icon: "🍔" },
  { id: "footlong-sandwich", name: "Footlong Sandwich", slug: "footlong-sandwich", icon: "🥖" },
  { id: "french-fries", name: "French Fries & Starters", slug: "french-fries", icon: "🍟" },
  { id: "garlic-bread", name: "Garlic Bread", slug: "garlic-bread", icon: "🥖" },
  { id: "coffee-hot", name: "Hot Coffee", slug: "coffee", icon: "☕" },
  { id: "coffee-cold", name: "Cold Coffee", slug: "coffee", icon: "🧊" },
  { id: "milkshake", name: "Milkshakes", slug: "milkshakes", icon: "🥤" },
  { id: "mocktail", name: "Mocktails", slug: "mojito", icon: "🍹" },
] as const
